### ISSUE TITLE
Crash with new Buildcraft version

### ISSUE THREAD

**Issue by SFort** [faceofcat/BC-eXtra-Pipes#2]
I'm using bc-extra-pipes-7.99.13-1
Updated from BC 7.99.13 to 7.99.14
Got the following crash:
[Pastebin](https://pastebin.com/ubM98nD6)

**Comment by faceofcat** [comment]
please try with this one: 
https://maven.modcrafters.net/net/ndrei/bc-extra-pipes/7.99.14-1/

there was an API change between 7.99.13 and 7.99.14.

**Comment by TheLimePixel** [comment]
When will this version be out?

**Comment by faceofcat** [comment]
just did... might take a while for curseforge to get it approved and such.
