### ISSUE TITLE
Fluid pipes wont work

### ISSUE THREAD

**Issue by deadguy108** [faceofcat/BC-eXtra-Pipes#6]
i have 2 fluid pipes trying to transport oil and it wont send the the oil to the reciever. dont know if i am supposed to link the pipes somehow but please help

**Comment by faceofcat** [comment]
you are supposed to paint the pipes the same color... using BuildCraft's brush thingy.

**Comment by faceofcat** [comment]
just tested in latest version... fluid pipes work ok... just make sure to: 
1. paint sender and receiver the same color (using buildcraft's paintbrush)
2. both sender and receiver are in loaded chunks (they won't chunk load themselves)
